name: FluentMAUI Build

on:
  workflow_dispatch:

env:
  Version: 8.0.${{ github.run_number }}

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Build FluentMAUI.Core
        uses: .github/actions/dotnet-maui-build
        with:
          version: ${{ env.Version }}
          project: source/FluentMAUI.Core/FluentMAUI.Core.csproj
          nugetPackage: source/FluentMAUI.Core/**/*.nupkg

      - name: Build FluentMAUI.Configuration
        uses: .github/actions/dotnet-maui-build
        with:
          version: ${{ env.Version }}
          project: source/FluentMAUI.Configuration/FluentMAUI.Configuration.csproj
          nugetPackage: source/FluentMAUI.Configuration/**/*.nupkg

      - name: Build FluentMAUI.UI
        uses: .github/actions/dotnet-maui-build
        with:
          version: ${{ env.Version }}
          project: source/FluentMAUI.UI/FluentMAUI.UI.csproj
          nugetPackage: source/FluentMAUI.UI/**/*.nupkg
 
  post-build:
    runs-on: linux-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set Version Git Tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}